-- =====================================================================================
-- BOOTSTRAP: Deployment framework tables + package
-- Run ONCE per environment (same schema that owns App 1200 objects).
-- =====================================================================================

-- 1) TABLES
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE deploy_bundles (
      bundle_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      app_id        NUMBER NOT NULL,
      version_tag   VARCHAR2(64) NOT NULL,
      created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      created_by    VARCHAR2(128) DEFAULT USER NOT NULL,
      manifest_json CLOB NOT NULL,
      bundle_zip    BLOB NOT NULL,
      sha256        VARCHAR2(64),
      CONSTRAINT deploy_bundles_uq UNIQUE (app_id, version_tag)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF; -- already exists
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE deploy_runs (
      run_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      bundle_id     NUMBER,
      action        VARCHAR2(30) NOT NULL, -- EXPORT|DEPLOY|PUBLISH|PULL
      status        VARCHAR2(20) NOT NULL, -- RUNNING|SUCCESS|FAILED
      started_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      ended_at      TIMESTAMP,
      error_stack   CLOB,
      log_clob      CLOB,
      CONSTRAINT deploy_runs_fk FOREIGN KEY (bundle_id) REFERENCES deploy_bundles(bundle_id)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE deploy_applied (
      applied_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      bundle_id     NUMBER NOT NULL,
      applied_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      applied_by    VARCHAR2(128) DEFAULT USER NOT NULL,
      result        VARCHAR2(20) NOT NULL, -- SUCCESS|FAILED
      details       CLOB,
      CONSTRAINT deploy_applied_fk FOREIGN KEY (bundle_id) REFERENCES deploy_bundles(bundle_id)
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE deploy_schema_migrations (
      migration_id VARCHAR2(200) PRIMARY KEY,
      applied_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      applied_by   VARCHAR2(128) DEFAULT USER NOT NULL,
      bundle_id    NUMBER,
      notes        VARCHAR2(4000)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF; -- already exists
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE deploy_migration_scripts (
      migration_id   VARCHAR2(200) PRIMARY KEY, -- e.g. 0001_add_col_x.sql
      script_clob    CLOB NOT NULL,
      created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      created_by     VARCHAR2(128) DEFAULT USER NOT NULL,
      active         CHAR(1) DEFAULT 'Y' CHECK (active IN ('Y','N'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/