CREATE USER "OCI_FOCUS_REPORTS" DEFAULT COLLATION "USING_NLS_COMP" 
   DEFAULT TABLESPACE "DATA"
   TEMPORARY TABLESPACE "TEMP"
   IDENTIFIED BY &1;
ALTER USER "OCI_FOCUS_REPORTS" QUOTA UNLIMITED ON "DATA";
ALTER PROFILE "DEFAULT"
    LIMIT 
         PASSWORD_LIFE_TIME UNLIMITED;
-- REST ENABLE
BEGIN
    ORDS_ADMIN.ENABLE_SCHEMA(
        p_enabled => TRUE,
        p_schema => 'OCI_FOCUS_REPORTS',
        p_url_mapping_type => 'BASE_PATH',
        p_url_mapping_pattern => 'oci_focus_reports',
        p_auto_rest_auth=> FALSE
    );
    -- ENABLE DATA SHARING
    C##ADP$SERVICE.DBMS_SHARE.ENABLE_SCHEMA(
            SCHEMA_NAME => 'OCI_FOCUS_REPORTS',
            ENABLED => TRUE
    );
    commit;
END;
/
EXEC DBMS_AUTO_INDEX.CONFIGURE('AUTO_INDEX_MODE','IMPLEMENT');
EXEC DBMS_AUTO_INDEX.CONFIGURE('AUTO_INDEX_SCHEMA','OCI_FOCUS_REPORTS', TRUE);
EXEC DBMS_CLOUD_ADMIN.DISABLE_RESOURCE_PRINCIPAL();
EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL();
EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL(username => 'OCI_FOCUS_REPORTS');
EXEC DBMS_CLOUD_ADMIN.DISABLE_RESOURCE_PRINCIPAL();
EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL();
EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL(username => 'OCI_FOCUS_REPORTS');
GRANT EXECUTE ON "ADMIN"."OCI$RESOURCE_PRINCIPAL" TO "OCI_FOCUS_REPORTS";
GRANT SELECT ANY TABLE TO OCI_FOCUS_REPORTS;
GRANT CREATE ANY JOB TO OCI_FOCUS_REPORTS;
GRANT "CONNECT" TO OCI_FOCUS_REPORTS;
GRANT "RESOURCE" TO OCI_FOCUS_REPORTS;
GRANT "DWROLE" TO OCI_FOCUS_REPORTS;
GRANT "CONSOLE_DEVELOPER" TO OCI_FOCUS_REPORTS;
GRANT "OML_DEVELOPER" TO OCI_FOCUS_REPORTS;
GRANT CREATE ANY CONTEXT TO oci_focus_reports;
grant create table to oci_focus_reports;
grant create sequence to oci_focus_reports;
grant create view to oci_focus_reports;
grant create materialized view to oci_focus_reports;
grant create procedure to oci_focus_reports;
grant create trigger to oci_focus_reports;
grant create job to oci_focus_reports;

GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_OS_ORGANIZATION_SUBSCRIPTION_LIST_ORGANIZATION_SUBSCRIPTIONS_RESPONSE_T TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON c##cloud$service.dbms_cloud_oci_os_subscription_list_subscriptions_response_t TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_OS_ORGANIZATION_SUBSCRIPTION TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_OS_SUBSCRIPTION TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_ONESUBSCRIPTION_SUBSCRIPTION_CURRENCY_T TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_ONESUBSCRIPTION_SUBSCRIPTION_SUBSCRIBED_SERVICE_TBL TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_ONESUBSCRIPTION_SUBSCRIPTION_PRODUCT_T TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON C##CLOUD$SERVICE.DBMS_CLOUD_OCI_ONESUBSCRIPTION_COMMITMENT_SERVICE_TBL TO OCI_FOCUS_REPORTS;
grant execute on C##CLOUD$SERVICE.DBMS_CLOUD_OCI_MN_MONITORING to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_ID_IDENTITY to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_RS_RESOURCE_SEARCH to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DB_DATABASE_LIST_MAINTENANCE_RUN_HISTORY_RESPONSE_T to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DB_DATABASE to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DATABASE_MAINTENANCE_RUN_HISTORY_SUMMARY_T to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DATABASE_MAINTENANCE_RUN_HISTORY_SUMMARY_TBL to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DATABASE_UPDATE_AUTONOMOUS_DATABASE_DETAILS_T to OCI_FOCUS_REPORTS;
grant execute on dbms_cloud_oci_monitoring_list_metrics_details_t to OCI_FOCUS_REPORTS;
grant execute on dbms_cloud_oci_monitoring_summarize_metrics_data_details_t to OCI_FOCUS_REPORTS;
grant execute on c##cloud$service.dbms_cloud_oci_mn_monitoring_list_metrics_response_t to OCI_FOCUS_REPORTS;
grant execute on c##cloud$service.dbms_cloud_oci_mn_monitoring_summarize_metrics_data_response_t to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DB_DATABASE_UPDATE_AUTONOMOUS_DATABASE_RESPONSE_T to OCI_FOCUS_REPORTS;
grant execute on C##CLOUD$SERVICE.DBMS_CLOUD_OCI_DATABASE_MAINTENANCE_RUN_SUMMARY_T to OCI_FOCUS_REPORTS;
grant execute on C##CLOUD$SERVICE.DBMS_CLOUD_OCI_DATABASE_ESTIMATED_PATCHING_TIME_T to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_ID_IDENTITY_LIST_COMPARTMENTS_RESPONSE_T to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DB_DATABASE_LIST_EXADATA_INFRASTRUCTURES_RESPONSE_T to OCI_FOCUS_REPORTS;
grant execute on DBMS_CLOUD_OCI_DB_DATABASE_LIST_CLOUD_EXADATA_INFRASTRUCTURES_RESPONSE_T to OCI_FOCUS_REPORTS;
grant execute on c##cloud$service.dbms_cloud_oci_rs_resource_search_search_resources_response_t to OCI_FOCUS_REPORTS;
grant execute on c##cloud$service.dbms_cloud_oci_resource_search_structured_search_details_t to OCI_FOCUS_REPORTS;
grant execute on dbms_cloud_oci_identity_compartment_tbl to OCI_FOCUS_REPORTS;

GRANT EXECUTE ON DBMS_RESULT_CACHE TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON DBMS_CLOUD TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON DBMS_CRYPTO TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON DBMS_CLOUD_PIPELINE TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON DBMS_CLOUD_AI TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON CS_SESSION TO OCI_FOCUS_REPORTS;
GRANT EXECUTE ON OCI$RESOURCE_PRINCIPAL TO OCI_FOCUS_REPORTS;